export const noteBody = "https://face.baby/vocab#noteBody"
export const refs = "https://face.baby/vocab#refs"
export const hasFeedItem = "https://face.baby/vocab#hasFeedItem"
export const Credit = "https://face.baby/vocab#Credit"
export const Debit = "https://face.baby/vocab#Debit"
export const amount = "https://face.baby/vocab#amount"
export const accountOf = "https://face.baby/vocab#accountOf"
